# Generated by Django 4.0.5 on 2022-07-22 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_img_desktop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Img_Desc_Desktop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img_desc', models.ImageField(upload_to='product_img_desc_desktop')),
                ('product_img_desc_desktop', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
