# Generated by Django 4.0.5 on 2022-07-22 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_product_img_desc_desktop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Img_Color_Desktop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img_color', models.ImageField(upload_to='product_img_color_desktop')),
                ('product_img_color_desktop', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
