# Generated by Django 4.0.5 on 2022-07-22 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product_img_color_desktop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_img_desktop',
            old_name='product_img',
            new_name='product_img_desk',
        ),
        migrations.CreateModel(
            name='Product_Img_Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img_mob', models.ImageField(upload_to='product_img_mobile')),
                ('product_img_mobile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
