# Generated by Django 4.0.5 on 2022-07-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_product_img_product_img_desktop_product_img_desk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_img_color_desktop',
            old_name='product_img_color',
            new_name='product_img_color_desk',
        ),
        migrations.RenameField(
            model_name='product_img_desc_desktop',
            old_name='product_img_desc',
            new_name='product_img_desc_desk',
        ),
    ]
