# Generated by Django 4.0.5 on 2022-07-22 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_product_img_desc_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Img_Color_Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img_color_mob', models.ImageField(upload_to='product_img_color_mobile')),
                ('product_img_color_mobile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
