# Generated by Django 4.0.5 on 2022-07-28 15:00

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_product_img_color_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=django_countries.fields.CountryField(default=4, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='locality',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product_img_desktop',
            name='product_img_desk',
            field=models.ImageField(default=None, upload_to='product_img_desktop'),
        ),
    ]
