# Generated by Django 4.0.5 on 2022-08-11 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_customer_address_customer_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_details',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
